### ISSUE TITLE
mysqli_real_escape_string() is escaping 'false' values to empty string

### ISSUE THREAD

**Issue by jatubio** [stefangabos/Zebra_Database#67]
Hi,

After I upgraded to MySQL 8.0,  I'm getting a SQL error about `inserting a string value on an tinyint column` because mysqli_real_escape_string() is escaping 'false' values to "" in `escape()` method.

**Comment by jatubio** [comment]
I created this pull request with the changes that worked for me: https://github.com/stefangabos/Zebra_Database/pull/68

**Comment by stefangabos** [comment]
I am unable to confirm this
I created the following table
```sql
DROP TABLE IF EXISTS `test`;
CREATE TABLE `test` (
  `col` tinyint(4) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
then I did
```php
$db->insert('test', array(
    'col'   =>  false,
));
```

which translates to 
```sql
INSERT INTO `test` (`col`) 
VALUES 
    ("")
```
which, in turn, translates to `0` in the database

This is happening because `""` (empty string) is a value that equals `false` in a non-strict boolean context in PHP (and so does `0` or an empty array):

```php
echo '' == false;
echo array() == false;
echo 0 == false;
```

 If you replace the `false` with `true`, you'd get `1` which is how PHP's represents boolean `true` as a numeric value.

Under no circumstances should a PHP boolean `false` be translated to the "false" string - any string, other than an empty string, is `true` 

Please show me how to get that error when inserting a string value on an tinyint column and maybe we can come up with a good solution

**Comment by jatubio** [comment]
Hi, have you tried with MySQL 8.0 version?

What I need is to translate it to:

```
   INSERT INTO `test` (`col`) 
   VALUES 
       (false)

```       
Because MySQL 8.0 by default have this config:
`sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"` 

You can read more about that here:
https://stackoverflow.com/questions/8874647/general-error-1366-incorrect-integer-value-with-doctrine-2-1-and-zend-form-upda/8882396#8882396
https://stackoverflow.com/questions/28606483/how-to-allow-empty-string-for-integer-in-mysql

**Comment by stefangabos** [comment]
If `col` is `tinyint` then having
```sql
INSERT INTO `test` (`col`) 
VALUES 
    (false)
```
it's wrong...
you might want to try
```php
$db->insert('test', array(
    'col'   =>  $var === false ? 0 : $val,
));
```
...or something similar

but nevertheless, i'll look into it

**Comment by stefangabos** [comment]
actually, i don't think there's anything i can do, as the library doesn't know what data type you are expecting so escaping boolean FALSE to empty string seems fair enough as that is PHP's default behavior

**Comment by jatubio** [comment]
Ok, I understand your point of view. Thanks for your proposals, I'll look into them.

Thank you very much
